# Phoenix release image, the shape `mix phx.gen.release --docker` emits.
# Versions are build args so the caller (oci-build-push.yml build-args) can
# pass the ones from .tool-versions; the defaults are known-good pairs.
#
#   docker build --build-arg ELIXIR_VERSION=1.19.2 --build-arg OTP_VERSION=28.1.1 .
#
# Runtime contract (config/runtime.exs reads these at boot, never at build):
#   SECRET_KEY_BASE, DATABASE_URL, PHX_HOST, PORT (default 8080), PHX_SERVER=true
ARG ELIXIR_VERSION=1.19.2
ARG OTP_VERSION=28.1.1
ARG DEBIAN_VERSION=trixie-20260610-slim

ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"
ARG RUNNER_IMAGE="debian:${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE} AS builder

RUN apt-get update -y && apt-get install -y --no-install-recommends build-essential git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN mix local.hex --force && mix local.rebar --force

ENV MIX_ENV="prod"

# Deps first so the layer is cached until mix.lock changes.
COPY mix.exs mix.lock ./
RUN mix deps.get --only $MIX_ENV
RUN mkdir config
COPY config/config.exs config/${MIX_ENV}.exs config/
RUN mix deps.compile

COPY priv priv
COPY lib lib
COPY assets assets
RUN mix assets.deploy
RUN mix compile

# runtime.exs is copied AFTER compile: changes to it must not invalidate the build.
COPY config/runtime.exs config/
COPY rel rel
RUN mix release

FROM ${RUNNER_IMAGE}

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends libstdc++6 openssl libncurses6 locales ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8

WORKDIR /app
RUN chown nobody /app
ENV MIX_ENV="prod"

# Replace `my_app` with the release name from mix.exs.
COPY --from=builder --chown=nobody:root /app/_build/${MIX_ENV}/rel/my_app ./

USER nobody

# rel/overlays/bin/server sets PHX_SERVER=true then execs bin/my_app start;
# rel/overlays/bin/migrate runs MyApp.Release.migrate — both generated by
# `mix phx.gen.release`.
CMD ["/app/bin/server"]
